# This will error out because no pippete exist
equipment:
  - name: corning_96_wellplate_360ul_flat
    location: "1"
  - name: opentrons_96_tiprack_20ul #opentrons_96_tiprack_1000ul
    location: "8"
  - name: opentrons_96_tiprack_1000ul
    location: "9"
commands:
  - name: example command
    command: transfer
    source: A1
    destination: B1
    volume: 100

metadata:
  protocolName: Example Name
  author: Kyle khippe@anl.gov
  description: some detailed description
  apiLevel: "2.12"
